pipeline {
    agent any

    triggers {
        // 매 시간마다 트리거
        cron('H * * * *')
    }

    environment {
        DOCKER_IMAGE = 'chungdaeking/dashboard:dev'
        CONTAINER_NAME = 'dashboard'
        
        PORT = '3333'

        DATA_IO_PORT = '3001'
        DATA_IO_SCHEMA = 'http'
        DATA_IO_HOST = 'localhost'
    }

    stages {
        stage('Pull Docker Image') {
            steps {
                script {
                    // Docker Hub에서 최신 이미지 pull
                    sh "docker pull ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Stop and Remove Existing Container') {
            steps {
                script {
                    // 기존 컨테이너가 존재하면 중지하고 삭제
                    sh """
                    if [ \$(docker ps -al -q -f name=${CONTAINER_NAME}) ]; then
                        docker stop ${CONTAINER_NAME}
                        docker rm ${CONTAINER_NAME}
                    fi
                    """
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // 새로운 컨테이너 실행
                    sh """
                    docker run \\
                        -e PORT=${PORT} \\
                        -e DATA_IO_PORT=${DATA_IO_PORT} \\
                        -e DATA_IO_SCHEMA=${DATA_IO_SCHEMA} \\
                        -e DATA_IO_HOST=${DATA_IO_HOST} \\
                        -d \\
                        --name ${CONTAINER_NAME} \\
                        --network streamlit-network \\
                        -p ${PORT}:${PORT} \\
                        ${DOCKER_IMAGE}
                    """
                }
            }
        }
    }
}
